apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: {{ .Values.inferenceService.name }}
spec:
  predictor:
    serviceAccountName: {{ .Values.serviceAccount.name }}
    tensorflow:
      storageUri: {{ .Values.inferenceService.storageUri }}
