apiVersion: "kubeflow.org/v1"
kind: TFJob
metadata:
  name: {{ include "keras-mnist.fullname" . }}
spec:
  tfReplicaSpecs:
    Worker:
      replicas: {{ .Values.replicaCount }}
      restartPolicy: OnFailure
      template:
        spec:
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
          containers:
            - name: tensorflow
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: {{ .Values.command | toYaml | nindent 16 }} 
              # resources:
              #   requests:
              #     cpu: {{ .Values.resources.requests.cpu }}
              #     memory: {{ .Values.resources.requests.memory }}
              #   limits:
              #     cpu: {{ .Values.resources.limits.cpu }}
              #     memory: {{ .Values.resources.limits.memory }}
              env:
                {{- range .Values.env }}
                - name: {{ .name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .secretKeyRef.secretName }}
                      key: {{ .secretKeyRef.key }}
                {{- end }}