apiVersion: "kubeflow.org/v1"
kind: TFJob
metadata:
  name: {{ include "keras-mnist-training.fullname" . }}
spec:
  tfReplicaSpecs:
    Worker:
      replicas: {{ .Values.replicaCount }}
      restartPolicy: OnFailure
      template:
        spec:
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
          containers:
            - name: tensorflow
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - "{{ .Values.command }}"
