name: Deploy a k8s cluster

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        options: [ 'sbx' ]
        default: sbx
        description: 'Environment on which to deploy. Dev, qas, staging, prod environments not considered'
      AKS_VM_SIZE:
        type: choice
        options: [ 'Standard_B8ms', 'Standard_NC4as' ]
        default: Standard_B8ms
        description: 'AKS VM size. Search for Azure Bv1 sizes series VMs in a browser of choice'
      RESOURCE_INSTANCE_NUMBER:
        default: '001'
        description: '3-digit number considered when naming resources'
      LOCATION:
        type: choice
        options: [ 'West Europe', 'Switzerland', 'North Europe' ]
        default: West Europe
        description: 'The region where cloud resources will be deployed'

jobs:

  deploy-k8s:
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
      ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
      ARM_CLIENT_ID: '${{ secrets.ARM_CLIENT_ID }}'
      ARM_CLIENT_SECRET: '${{ secrets.ARM_CLIENT_SECRET }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3  
      
      - name: Terraform Init # requires a Storage Account backend deployed trough storage-account-backend-deploy workflow step
        run: |
          terraform init \
          -backend-config="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}" \
          -backend-config="storage_account_name=mopoctbsbxsa001" \
          -backend-config="resource_group_name=mopoctb-sbx-rg001" \
          -backend-config="container_name=mopoctbsbxsac001" \
          -backend-config="key=${{ inputs.ENVIRONMENT }}/cloud-infra/${{ inputs.RESOURCE_INSTANCE_NUMBER }}/terraform.tfstate"
        working-directory: ./terraform/envs/${{ inputs.ENVIRONMENT }}/cloud-infra

      - name: Deploy Kubernetes service and related resources
        run: terraform apply --auto-approve
        continue-on-error: false
        working-directory: ./terraform/envs/${{ inputs.ENVIRONMENT }}/cloud-infra
        env:
          TF_VAR_aks_vm_size: ${{ inputs.AKS_VM_SIZE }}
          TF_VAR_resource_instance_number: ${{ inputs.RESOURCE_INSTANCE_NUMBER }}
          TF_VAR_location: ${{ inputs.LOCATION }}