name: Deploy Container registry

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
          type: choice
          options: [ 'sbx' ]
          default: sbx
          description: 'Environment on which to deploy. Dev, qas, staging, prod environments not considered'

jobs:

  deploy-acr:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
      ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
      ARM_CLIENT_ID: '${{ secrets.ARM_CLIENT_ID }}'
      ARM_CLIENT_SECRET: '${{ secrets.ARM_CLIENT_SECRET }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3  
      - name: Terraform Init
        run: terraform init 
        working-directory: ./devops/terraform/acr
      - name: Deploy Azure Container registry
        run: terraform apply --auto-approve # Resources need to be manually deleted in Azure Portal
        continue-on-error: false
        working-directory: ./devops/terraform/acr